site_name: MCI | WING
repo_url: https://github.com/mciwing/mciwing.github.io
site_url: https://code-campus.at
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.top  # 'back to top' button on scrolling
    - header.autohide
    - search.highlight
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mciwing
copyright:
  © 2024 - 2025 | Manuel Ferdik & Jakob Klotz
nav:
  - Home: index.md

  - Python Crash Course:
    - Home: python/index.md
    - Installation: python/installation.md
    - IDE: python/ide.md
    - Variables: python/variables.md

    - Types:
      - Strings: python/types/strings.md
      - Integers & Floats: python/types/numbers.md
      - Boolean & None: python/types/bool_and_none.md

    - Comparisons & Logical Operators: python/comparisons_and_logic.md

    - Containers:
      - Lists: python/containers/list.md
      - Dictionaries: python/containers/dict.md
      - Tuples: python/containers/tuple.md

    - Control Structures:
      - Loops: python/control-structures/for.md
      - More Control Structures: python/control-structures/if.md

    - Functions: python/functions.md
    - Package Management: python/packages.md
    - Pandas: python/pandas.md

  - Python Extensive Course:
    - Home: python-extensive/index.md

    - Basics & Data Types:
      - Setup:
        - Installation: python-extensive/installation.md
        - IDE: python-extensive/ide.md

      - Variables: python-extensive/variables.md

      - Types:
        - Strings: python-extensive/types/strings.md
        - Integers & Floats: python-extensive/types/numbers.md
        - Boolean & None: python-extensive/types/bool_and_none.md

    - Logic & Containers:
      - Comparisons & Logical Operators: python-extensive/comparisons_and_logic.md

      - Containers:
        - Lists: python-extensive/containers/list.md
        - Dictionaries: python-extensive/containers/dict.md
        - Tuples: python-extensive/containers/tuple.md

    - Control Structures & Functions:
      - Control Structures:
        - Loops: python-extensive/control-structures/for.md
        - More Control Structures: python-extensive/control-structures/if.md

      - Functions: python-extensive/functions.md  # TODO: methods vs. functions; variable scope

    - Dev Tools & Data Handling:
      - Package Management: python-extensive/packages.md
      - Pandas: python-extensive/pandas.md
      - Plotting: python-extensive/plotting.md

    - Data Acquisition & Export:
      - Data Basics: python-extensive/DataBasics.md
      - Data Acquisition:
        - Tabular Data: python-extensive/data/tabular.md
        - API: python-extensive/data/api.md

    - Graphical User Interface:
      - Object-Oriented Programming: python-extensive/oop.md
      - Graphical User Interfaces with Tkinter: python-extensive/tkinter.md
      - Building Web Applications with Streamlit: python-extensive/streamlit.md
      - Tkinter vs Streamlit: python-extensive/tkinter_streamlit.md


  - Statistics:
    - statistics/index.md

    - Data Basics:
      - databasics/Terms.md
      - databasics/Data.md
      - "Data Basics": databasics/DataBasics.md

    - Descriptive Statistics:
      - Univariate Methods:
        - statistics/univariate/Frequency.md
        - statistics/univariate/CentralTend.md
        - statistics/univariate/Dispersion.md
      - Bivariate Methods:
        - statistics/bivariate/Frequency.md
        - statistics/bivariate/Correlation.md
    - Inferential Statistics:
      - Probability Theory:
        - statistics/probability/General.md
        - statistics/probability/Sampling.md
        - statistics/probability/LawOfLargeNumbers.md
        - statistics/probability/CentralLimitTheorem.md
      - Hypothesis Testing:
        - statistics/hypothesis/General.md
        - statistics/hypothesis/Testing.md
        - statistics/hypothesis/Metrics.md
        - statistics/hypothesis/Ttest.md
        - statistics/hypothesis/ANOVA.md
      - Regression Analysis:
        - statistics/regression/LinearRegression.md

  - Data Science:
      - Home: data-science/index.md

      - Data Basics:
        - Definition of Key Terms: data-science/data-basics/terms.md
        - Data vs. Big Data: data-science/data-basics/data.md
        - Data Basics: data-science/data-basics/basics.md

      - Data Preparation & Preprocessing:
        - Data Preparation: data-science/data/preparation.md
        - Data Preprocessing: data-science/data/preprocessing.md

      - Supervised vs. Unsupervised Learning:
        - Introduction: data-science/algorithms/index.md

        - Supervised:
          - Regression: data-science/algorithms/supervised/regression.md
          - Classification: data-science/algorithms/supervised/classification.md
          - Tree Based:
            - Decision Tree: data-science/algorithms/supervised/tree-based/cart.md
            - Random Forest: data-science/algorithms/supervised/tree-based/forest.md

        - Unsupervised:
          - Clustering: data-science/algorithms/unsupervised/clustering.md
          - Dimensionality Reduction: data-science/algorithms/unsupervised/dim-reduction.md

      - Data Science in Practice:
          - Introduction: data-science/practice/index.md
          - 1. Data Preparation: data-science/practice/data-preparation.md
          - 2. Modelling: data-science/practice/modelling.md
          - 3. End-to-End: data-science/practice/end-to-end.md
          - Bonus: data-science/practice/bonus.md

  - Computer Vision: 
    - yolo/index.md
    - yolo/approaches.md
    - yolo/yolo.md
    - Image Processing 📷:
      - yolo/image/detection.md
      - yolo/image/segmentation.md
      - yolo/image/kp-extraction.md
    - Video Processing 🎥:
      - yolo/video/index.md
      - yolo/video/solutions.md
    - Train a Model 🏋️: 
      - yolo/train/index.md
      - yolo/train/acquisition.md
      - yolo/train/annotation.md
      - yolo/train/training.md
      - yolo/train/inference.md
  
  - MicroPython:
    - micropython/index.md
    - micropython/setup.md
    - micropython/sensors.md
    - micropython/actuator.md
    - micropython/mqtt.md
    - micropython/system.md
  
  - Projects & Blog:
    - Home: blog/index.md



plugins:
  - search
  - blog
  - tags
  - git-revision-date-localized:
      # has an impact on build time
      enable_creation_date: false
      type: timeago
      exclude:
        - index.md
        # has an issue with git --follow
        # see https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enable_git_follow
        - python-extensive/data/api.md
        # posts have their own date displayed in metadata
        - blog/*
      enabled: !ENV [ENABLE_GIT_REVISION_DATE, true]

  - git-authors:
      show_email_address: false
      sort_authors_by: "contribution"
      enabled: !ENV [ENABLE_GIT_AUTHORS, true]
      enabled_on_serve: !ENV [ENABLE_GIT_AUTHORS_SERVE, true]
      fallback_to_empty: false
      exclude:
        - blog/*
        # Content added with include-markdown plugin that would display the
        # wrong author
        - python-extensive/DataBasics.md
        - data-science/data-basics/*
        - data-science/algorithms/supervised/regression.md

  - include-markdown
  - mkdocs_quiz

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:  # enable icons/emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:  # to activate diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.keys  # render keyboard shortcuts
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.tabbed:  # enable content tabs
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css