site_name: MCI | WING
repo_url: https://github.com/mciwing/mciwing.github.io
site_url: https://mciwing.github.io
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: teal
    accent: pink
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.top  # 'back to top' button on scrolling
    - header.autohide
    - search.highlight
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mciwing
copyright:
  MCI | Industrial Engineering & Management<br>
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 
    - Manuel Ferdik, Jakob Klotz
nav:
  - Home: index.md

  - Python Crash Course:
    - python/index.md
    - python/installation.md
    - python/ide.md
    - python/variables.md

    - Types:
      - python/types/strings.md
      - python/types/numbers.md
      - python/types/bool_and_none.md

    - python/comparisons_and_logic.md

    - Containers:
      - python/containers/list.md
      - python/containers/dict.md
      - python/containers/tuple.md

    - Control Structures:
      - python/control-structures/for.md
      - python/control-structures/if.md

    - python/functions.md
    - python/packages.md
    - python/pandas.md

  - Python Extensive Course:
    - Home: python-extensive/index.md

    - Basics & Data Types:
      - Setup:
        - python-extensive/installation.md
        - "IDE": python-extensive/ide.md

      - python-extensive/variables.md

      - Types:
        - python-extensive/types/strings.md
        - python-extensive/types/numbers.md
        - python-extensive/types/bool_and_none.md

    - Logic & Containers:
      - python-extensive/comparisons_and_logic.md

      - Containers:
        - python-extensive/containers/list.md
        - python-extensive/containers/dict.md
        - python-extensive/containers/tuple.md

    - Control Structures & Functions:
      - Control Structures:
        - python-extensive/control-structures/for.md
        - python-extensive/control-structures/if.md

      - python-extensive/functions.md  # TODO: methods vs. functions; variable scope

    - Dev Tools & Data Handling:
      - python-extensive/packages.md
      - python-extensive/pandas.md
      - python-extensive/plotting.md

    - Data Acquisition & Export:
      - "Data Basics": python-extensive/DataBasics.md
      - "Data Acquisition":
        - python-extensive/data/tabular.md
        - python-extensive/data/api.md

    - Graphical User Interface:
      - python-extensive/oop.md
      - python-extensive/tkinter.md
      - python-extensive/streamlit.md

  - Statistics:
    - statistics/index.md

    - Data Basics:
      - databasics/Terms.md
      - databasics/Data.md
      - "Data Basics": databasics/DataBasics.md

    - Descriptive Statistics:
      - Univariate Methods:
        - statistics/univariate/Frequency.md
        - statistics/univariate/CentralTend.md
        - statistics/univariate/Dispersion.md
      - Bivariate Methods:
        - statistics/bivariate/Frequency.md
        - statistics/bivariate/Correlation.md
    - Inferential Statistics:
      - Probability Theory:
        - statistics/probability/General.md
        - statistics/probability/Sampling.md
        - statistics/probability/LawOfLargeNumbers.md
        - statistics/probability/CentralLimitTheorem.md
      - Hypothesis Testing:
        - statistics/hypothesis/General.md
        - statistics/hypothesis/Testing.md
        - statistics/hypothesis/Metrics.md
        - statistics/hypothesis/Ttest.md
        - statistics/hypothesis/ANOVA.md
      - Regression Analysis:
        - statistics/regression/LinearRegression.md

  - Data Science:
      - data-science/index.md

      - Data Basics:
        - data-science/data-basics/terms.md
        - data-science/data-basics/data.md
        - "Data Basics": data-science/data-basics/basics.md

      - Data Preparation & Preprocessing:
        - data-science/data/preparation.md
        - data-science/data/preprocessing.md

      - Supervised vs. Unsupervised Learning:
        - data-science/algorithms/index.md

        - Supervised:
          - data-science/algorithms/supervised/regression.md
          - data-science/algorithms/supervised/classification.md
          - Tree based:
            - Decision Tree: data-science/algorithms/supervised/tree-based/cart.md
            - Random Forest: data-science/algorithms/supervised/tree-based/forest.md

        - Unsupervised:
          - data-science/algorithms/unsupervised/clustering.md
          - data-science/algorithms/unsupervised/dim-reduction.md

      - Data Science in Practice:
          - Introduction: data-science/practice/index.md
          - 1. Data preparation: data-science/practice/data-preparation.md  # TODO update links to Markdown files
          - 2. Modelling: data-science/practice/modelling.md
          - 3. End-to-End: data-science/practice/end-to-end.md

  - Computer Vision: 
    - yolo/index.md
    - yolo/approaches.md
    - yolo/yolo.md
    - Image Processing 📷:
      - yolo/image/detection.md
      - yolo/image/segmentation.md
      - yolo/image/kp-extraction.md
    - Video Processing 🎥:
      - yolo/video/index.md
      - yolo/video/solutions.md
    - Train a Model: 
      - yolo/train/acquisition.md
      - yolo/train/annotation.md
      - yolo/train/training.md
      - yolo/train/inference.md


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      exclude:
        - index.md
      enabled: !ENV [ENABLE_GIT_REVISION_DATE, true]
  - git-committers:
      repository: mciwing/mciwing.github.io
      branch: main
      enabled: !ENV [ENABLE_GIT_COMMITTERS, true]
      token: !ENV MKDOCS_GIT_COMMITTERS_APIKEY
  - table-reader
  - include-markdown
  - mkdocs_quiz

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:  # enable icons/emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:  # to activate diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.keys  # render keyboard shortcuts
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.tabbed:  # enable content tabs
        alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css