site_name: MCI | WING
repo_url: https://github.com/mciwing/mciwing.github.io
site_url: https://mciwing.github.io
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: teal
    accent: pink
  icon:
    repo: fontawesome/brands/git-alt

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - navigation.footer
    - navigation.top  # 'back to top' button on scrolling
    - header.autohide
    - search.highlight
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mciwing
copyright:
  MCI | Industrial Engineering & Management<br>
  <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 
    - Manuel Ferdik, Jakob Klotz
nav:
  - Home: index.md

  - Python Crash Course:
    - python/index.md
    - python/installation.md
    - python/ide.md
    - python/variables.md

    - Types:
      - python/types/strings.md
      - python/types/numbers.md
      - python/types/bool_and_none.md

    - python/comparisons_and_logic.md

    - Containers:
      - python/containers/list.md
      - python/containers/dict.md
      - python/containers/tuple.md

    - Control Structures:
      - python/control-structures/for.md
      - python/control-structures/if.md

    - python/functions.md
    - python/packages.md
    - python/pandas.md

  - Python Extensive Course:
      - programming/index.md  # TODO: remove if all materials are finished

      - Basics & Data Types:
          - python/index.md  # TODO: rework specific mentions on the Crash Course

          - Setup:
              - python/installation.md
              - python/ide.md

          - python/variables.md

          - Types:
              - python/types/strings.md
              - python/types/numbers.md
              - python/types/bool_and_none.md

      - Logic & Containers:
          - python/comparisons_and_logic.md

          - Containers:
              - python/containers/list.md
              - python/containers/dict.md
              - python/containers/tuple.md

      - Control Structures & Functions:
          - Control Structures:
              - python/control-structures/for.md
              - python/control-structures/if.md

          - python/functions.md  # TODO: methods vs. functions; variable scope

      - Dev Tools & Data Handling:
          - python/packages.md
          - python/pandas.md  # TODO: emphasis on loading files; reading docs;
          # more in-depth about pandas functionalities
          - programming/plotting.md  # TODO: plotting with pandas

      - Data Acquisition & Export:
          - databasics/DataBasics.md
          - programming/data/retrieval.md  # TODO: practical tips on data retrieval
          - programming/data/export.md  # TODO: how to write files

      - Graphical User Interface:
          - programming/oop.md  # TODO: objet oriented programming
          - programming/gui.md  # TODO: graphical user interfaces

      - programming/git.md  # TODO: Bonus chapter on Git

  - Statistics:
    - statistics/index.md

    - Data Basics:
        - databasics/Terms.md
        - databasics/Data.md
        - databasics/DataBasics.md

    - Descriptive Statistics:
      - Univariate Methods:
        - statistics/univariate/Frequency.md
        - statistics/univariate/CentralTend.md
        - statistics/univariate/Dispersion.md
      - Bivariate Methods:
        - statistics/bivariate/Frequency.md
        - statistics/bivariate/Correlation.md
    - Inferential Statistics:
      - Probability Theory:
        - statistics/probability/General.md
        - statistics/probability/Sampling.md
        - statistics/probability/LawOfLargeNumbers.md
        - statistics/probability/CentralLimitTheorem.md
      - Hypothesis Testing:
        - statistics/hypothesis/General.md
        - statistics/hypothesis/Testing.md
        - statistics/hypothesis/Metrics.md
        - statistics/hypothesis/Ttest.md
        - statistics/hypothesis/ANOVA.md
      - Regression Analysis:
        - statistics/regression/LinearRegression.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - git-committers:
      repository: mciwing/mciwing.github.io
      branch: main
  - table-reader

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:  # enable icons/emojis
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys  # render keyboard shortcuts
  - pymdownx.critic
  - pymdownx.tilde
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.tabbed:  # enable content tabs
        alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css