authors:
  jakob:
    name: Jakob Klotz
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/177755923?v=4

  armin_muzaferovic:
    name: Armin Muzaferovic
    description: Student
    avatar: https://avatars.githubusercontent.com/u/152180657?v=4